# Generated by Django 4.0.3 on 2022-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pword', models.CharField(max_length=100)),
                ('cpword', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='intel',
        ),
    ]
