# Generated by Django 4.0.3 on 2022-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_delete_intel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='user_data',
        ),
    ]
