# Generated by Django 4.0.3 on 2022-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_intel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intel',
            name='id',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
