# Generated by Django 4.0.3 on 2022-05-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_login_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='cpword',
        ),
    ]
