# Generated by Django 4.0.3 on 2022-05-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_data_cpword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='details',
        ),
    ]
