# Generated by Django 4.0.3 on 2022-05-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_user_data_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
    ]
