# Generated by Django 4.0.3 on 2022-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_details_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='dept',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
