# Generated by Django 4.0.3 on 2022-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_detail_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='name',
        ),
        migrations.AddField(
            model_name='detail',
            name='first',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='last',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='other',
            field=models.CharField(default='', max_length=100),
        ),
    ]
