# Generated by Django 4.0.3 on 2022-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_detail_name_detail_first_detail_last_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='pword',
        ),
        migrations.AddField(
            model_name='detail',
            name='faculty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='dept',
            field=models.CharField(default='', max_length=100),
        ),
    ]
